name: Deploy website
on:
  push:
    branches:
      - main
    paths:
      - "01 Starting Project/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: "./01 Starting Project"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish JS Asset filename
        id: publish
        # I must keep in mind my script-file outputs
        # Uses find inside dist/ to capture the first .js filename cleanly
        run: |
          FILE_NAME=$(find dist -type f -name "*.js" -exec basename {} \; | head -n 1)
          echo "script-file=$FILE_NAME" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: |
            01 Starting Project/dist
            # Add any other files or directories you want to include in the artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist-files
          path: 01 Starting Project/dist
      - name: Output contents
        run: ls
      - name: Output script-file
        run: echo "Script file ${{needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."
