name: Get Issues Context
on:
  workflow_run:
    workflows: ["Build and Deploy Project"]
    types: [completed]
  workflow_dispatch:
  issues:
    types:
      [
        closed,
        opened,
        edited,
        deleted,
        pinned,
        unpinned,
        transferred,
        assigned,
        unassigned,
        labeled,
        unlabeled,
        locked,
        unlocked,
      ]

defaults:
  run:
    working-directory: "./04 Practice Project (Start)"

jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Print issues context
        run: |
          echo "Issues Number ${{ github.event.issue.number }}"
          echo "Issues Title ${{ github.event.issue.title }}"
          echo "Issue Context ${{ toJSON(github.event.issue) }}"
